"""Add contracts relations into Client

Revision ID: 6a606ee19796
Revises: ecf7bf3bb6dc
Create Date: 2025-02-27 10:10:30.506656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a606ee19796'
down_revision: Union[str, None] = 'ecf7bf3bb6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
