"""Add bidirectional relationship between User and Client

Revision ID: 88a24c0a4cba
Revises: 992e9bde105a
Create Date: 2025-02-27 08:55:33.571571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a24c0a4cba'
down_revision: Union[str, None] = '992e9bde105a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
