services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - src/database/.env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: